Added missing dependency
This fixes the following mypy error:

   tests/unit/cmk/plugins/gcp/special_agent/test_agent_gcp.py:11:1: error: Module "google.cloud" has no attribute "asset_v1"  [attr-defined]

For some weird reason, this only showed up after
disabling caching in b09c9f4429f9.

Change-Id: Ie9ec543d3b93eaafa905cc5b07afe42e8c54c691